name: Index Action for Eigenbot
description: TODO
branding:
  icon: package
  color: gray-dark
inputs:
  access-key:
    description: Eigenbot Access Key
    required: true
  github-token:
    description: GitHub Access Token
    required: false
  dir:
    description: Private Actions Directory
    default: .
runs:
  using: node16
  main: ./dist/main.js
