name: Index Action for Eigenbot
description: TODO
branding:
  icon: package
  color: gray-dark
inputs:
  version:
    description: TODO
    default: latest
  access-key:
    description: Eigenbot Access Key
    required: true
  dir:
    description: Private Actions Directory
    default: .
  repo:
    description: TODO
  ref:
    description: TODO
  sha:
    description: TODO
outputs:
  manifest-id:
    value: ${{ steps.index.outputs.manifest-id }}
    description: TODO
runs:
  using: composite
  steps:
    - id: index
      run: |
        ${{ github.action_path }}/bin/index \
          -access-key "${{ inputs.access-key }}" \
          -root "${{ github.workspace }}" \
          -dir "${{ inputs.dir }}" \
          -repo "${{ inputs.repo }}" \
          -ref "${{ inputs.ref }}" \
          -sha "${{ inputs.sha }}"
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ inputs.github-token }}
