name: Publish
on:
  release:
    types:
      - published
env:
  APP_ID: 284028
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: token
        with:
          app_id: ${{env.APP_ID}}
          private_key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
          repository: ${{ github.repository }}
          permissions: >-
            {"contents": "write"}
